/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Category = { 'phishing' : null } |
  { 'passwords' : null } |
  { 'safeBrowsing' : null } |
  { 'mobileSecurity' : null } |
  { 'emailSafety' : null } |
  { 'malware' : null };
export interface CheckResult {
  'contact' : string,
  'wasBreached' : boolean,
  'timestamp' : Time,
}
export type PaymentMethod = { 'upi' : null } |
  { 'netbanking' : null } |
  { 'card' : null };
export type PlanType = { 'premium' : null } |
  { 'elite' : null } |
  { 'super' : null };
export interface Subscription {
  'startTime' : Time,
  'paymentMethod' : PaymentMethod,
  'endTime' : [] | [Time],
  'paymentReference' : string,
  'userContact' : string,
  'planType' : PlanType,
}
export type Time = bigint;
export interface Tip {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'category' : Category,
}
export interface _SERVICE {
  'addTip' : ActorMethod<[string, string, Category], bigint>,
  'cancelSubscription' : ActorMethod<[string], undefined>,
  'getAllTips' : ActorMethod<[], Array<Tip>>,
  'getCheckHistory' : ActorMethod<[string], Array<CheckResult>>,
  'getSubscription' : ActorMethod<[string], Subscription>,
  'getTipsByCategory' : ActorMethod<[Category], Array<Tip>>,
  'submitCheck' : ActorMethod<[string], boolean>,
  'submitSupportMessage' : ActorMethod<[string, string, string], undefined>,
  'subscribe' : ActorMethod<
    [string, PlanType, PaymentMethod, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];