/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Category = IDL.Variant({
  'phishing' : IDL.Null,
  'passwords' : IDL.Null,
  'safeBrowsing' : IDL.Null,
  'mobileSecurity' : IDL.Null,
  'emailSafety' : IDL.Null,
  'malware' : IDL.Null,
});
export const Tip = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'category' : Category,
});
export const Time = IDL.Int;
export const CheckResult = IDL.Record({
  'contact' : IDL.Text,
  'wasBreached' : IDL.Bool,
  'timestamp' : Time,
});
export const PaymentMethod = IDL.Variant({
  'upi' : IDL.Null,
  'netbanking' : IDL.Null,
  'card' : IDL.Null,
});
export const PlanType = IDL.Variant({
  'premium' : IDL.Null,
  'elite' : IDL.Null,
  'super' : IDL.Null,
});
export const Subscription = IDL.Record({
  'startTime' : Time,
  'paymentMethod' : PaymentMethod,
  'endTime' : IDL.Opt(Time),
  'paymentReference' : IDL.Text,
  'userContact' : IDL.Text,
  'planType' : PlanType,
});

export const idlService = IDL.Service({
  'addTip' : IDL.Func([IDL.Text, IDL.Text, Category], [IDL.Nat], []),
  'cancelSubscription' : IDL.Func([IDL.Text], [], []),
  'getAllTips' : IDL.Func([], [IDL.Vec(Tip)], ['query']),
  'getCheckHistory' : IDL.Func([IDL.Text], [IDL.Vec(CheckResult)], ['query']),
  'getSubscription' : IDL.Func([IDL.Text], [Subscription], ['query']),
  'getTipsByCategory' : IDL.Func([Category], [IDL.Vec(Tip)], ['query']),
  'submitCheck' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'submitSupportMessage' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'subscribe' : IDL.Func([IDL.Text, PlanType, PaymentMethod, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Category = IDL.Variant({
    'phishing' : IDL.Null,
    'passwords' : IDL.Null,
    'safeBrowsing' : IDL.Null,
    'mobileSecurity' : IDL.Null,
    'emailSafety' : IDL.Null,
    'malware' : IDL.Null,
  });
  const Tip = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'category' : Category,
  });
  const Time = IDL.Int;
  const CheckResult = IDL.Record({
    'contact' : IDL.Text,
    'wasBreached' : IDL.Bool,
    'timestamp' : Time,
  });
  const PaymentMethod = IDL.Variant({
    'upi' : IDL.Null,
    'netbanking' : IDL.Null,
    'card' : IDL.Null,
  });
  const PlanType = IDL.Variant({
    'premium' : IDL.Null,
    'elite' : IDL.Null,
    'super' : IDL.Null,
  });
  const Subscription = IDL.Record({
    'startTime' : Time,
    'paymentMethod' : PaymentMethod,
    'endTime' : IDL.Opt(Time),
    'paymentReference' : IDL.Text,
    'userContact' : IDL.Text,
    'planType' : PlanType,
  });
  
  return IDL.Service({
    'addTip' : IDL.Func([IDL.Text, IDL.Text, Category], [IDL.Nat], []),
    'cancelSubscription' : IDL.Func([IDL.Text], [], []),
    'getAllTips' : IDL.Func([], [IDL.Vec(Tip)], ['query']),
    'getCheckHistory' : IDL.Func([IDL.Text], [IDL.Vec(CheckResult)], ['query']),
    'getSubscription' : IDL.Func([IDL.Text], [Subscription], ['query']),
    'getTipsByCategory' : IDL.Func([Category], [IDL.Vec(Tip)], ['query']),
    'submitCheck' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'submitSupportMessage' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'subscribe' : IDL.Func(
        [IDL.Text, PlanType, PaymentMethod, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };