/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Subscription {
    startTime: Time;
    paymentMethod: PaymentMethod;
    endTime?: Time;
    paymentReference: string;
    userContact: string;
    planType: PlanType;
}
export interface CheckResult {
    contact: string;
    wasBreached: boolean;
    timestamp: Time;
}
export interface Tip {
    id: bigint;
    title: string;
    content: string;
    category: Category;
}
export type Time = bigint;
export enum Category {
    phishing = "phishing",
    passwords = "passwords",
    safeBrowsing = "safeBrowsing",
    mobileSecurity = "mobileSecurity",
    emailSafety = "emailSafety",
    malware = "malware"
}
export enum PaymentMethod {
    upi = "upi",
    netbanking = "netbanking",
    card = "card"
}
export enum PlanType {
    premium = "premium",
    elite = "elite",
    super_ = "super"
}
export interface backendInterface {
    addTip(title: string, content: string, category: Category): Promise<bigint>;
    cancelSubscription(userContact: string): Promise<void>;
    getAllTips(): Promise<Array<Tip>>;
    getCheckHistory(contact: string): Promise<Array<CheckResult>>;
    getSubscription(userContact: string): Promise<Subscription>;
    getTipsByCategory(category: Category): Promise<Array<Tip>>;
    submitCheck(contact: string): Promise<boolean>;
    submitSupportMessage(name: string, email: string, message: string): Promise<void>;
    subscribe(userContact: string, planType: PlanType, paymentMethod: PaymentMethod, paymentReference: string): Promise<void>;
}
import type { Category as _Category, PaymentMethod as _PaymentMethod, PlanType as _PlanType, Subscription as _Subscription, Time as _Time, Tip as _Tip } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addTip(arg0: string, arg1: string, arg2: Category): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addTip(arg0, arg1, to_candid_Category_n1(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTip(arg0, arg1, to_candid_Category_n1(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async cancelSubscription(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.cancelSubscription(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelSubscription(arg0);
            return result;
        }
    }
    async getAllTips(): Promise<Array<Tip>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTips();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTips();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCheckHistory(arg0: string): Promise<Array<CheckResult>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCheckHistory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCheckHistory(arg0);
            return result;
        }
    }
    async getSubscription(arg0: string): Promise<Subscription> {
        if (this.processError) {
            try {
                const result = await this.actor.getSubscription(arg0);
                return from_candid_Subscription_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSubscription(arg0);
            return from_candid_Subscription_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTipsByCategory(arg0: Category): Promise<Array<Tip>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTipsByCategory(to_candid_Category_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTipsByCategory(to_candid_Category_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitCheck(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.submitCheck(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitCheck(arg0);
            return result;
        }
    }
    async submitSupportMessage(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitSupportMessage(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitSupportMessage(arg0, arg1, arg2);
            return result;
        }
    }
    async subscribe(arg0: string, arg1: PlanType, arg2: PaymentMethod, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.subscribe(arg0, to_candid_PlanType_n15(this._uploadFile, this._downloadFile, arg1), to_candid_PaymentMethod_n17(this._uploadFile, this._downloadFile, arg2), arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.subscribe(arg0, to_candid_PlanType_n15(this._uploadFile, this._downloadFile, arg1), to_candid_PaymentMethod_n17(this._uploadFile, this._downloadFile, arg2), arg3);
            return result;
        }
    }
}
function from_candid_Category_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Category): Category {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentMethod_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentMethod): PaymentMethod {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_PlanType_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PlanType): PlanType {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_Subscription_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Subscription): Subscription {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_Tip_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Tip): Tip {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    content: string;
    category: _Category;
}): {
    id: bigint;
    title: string;
    content: string;
    category: Category;
} {
    return {
        id: value.id,
        title: value.title,
        content: value.content,
        category: from_candid_Category_n6(_uploadFile, _downloadFile, value.category)
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    startTime: _Time;
    paymentMethod: _PaymentMethod;
    endTime: [] | [_Time];
    paymentReference: string;
    userContact: string;
    planType: _PlanType;
}): {
    startTime: Time;
    paymentMethod: PaymentMethod;
    endTime?: Time;
    paymentReference: string;
    userContact: string;
    planType: PlanType;
} {
    return {
        startTime: value.startTime,
        paymentMethod: from_candid_PaymentMethod_n10(_uploadFile, _downloadFile, value.paymentMethod),
        endTime: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.endTime)),
        paymentReference: value.paymentReference,
        userContact: value.userContact,
        planType: from_candid_PlanType_n13(_uploadFile, _downloadFile, value.planType)
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    upi: null;
} | {
    netbanking: null;
} | {
    card: null;
}): PaymentMethod {
    return "upi" in value ? PaymentMethod.upi : "netbanking" in value ? PaymentMethod.netbanking : "card" in value ? PaymentMethod.card : value;
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    premium: null;
} | {
    elite: null;
} | {
    super: null;
}): PlanType {
    return "premium" in value ? PlanType.premium : "elite" in value ? PlanType.elite : "super" in value ? PlanType.super : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    phishing: null;
} | {
    passwords: null;
} | {
    safeBrowsing: null;
} | {
    mobileSecurity: null;
} | {
    emailSafety: null;
} | {
    malware: null;
}): Category {
    return "phishing" in value ? Category.phishing : "passwords" in value ? Category.passwords : "safeBrowsing" in value ? Category.safeBrowsing : "mobileSecurity" in value ? Category.mobileSecurity : "emailSafety" in value ? Category.emailSafety : "malware" in value ? Category.malware : value;
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Tip>): Array<Tip> {
    return value.map((x)=>from_candid_Tip_n4(_uploadFile, _downloadFile, x));
}
function to_candid_Category_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): _Category {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_PaymentMethod_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod): _PaymentMethod {
    return to_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function to_candid_PlanType_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PlanType): _PlanType {
    return to_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PlanType): {
    premium: null;
} | {
    elite: null;
} | {
    super: null;
} {
    return value == PlanType.premium ? {
        premium: null
    } : value == PlanType.elite ? {
        elite: null
    } : value == PlanType.super ? {
        super_: null
    } : value;
}
function to_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod): {
    upi: null;
} | {
    netbanking: null;
} | {
    card: null;
} {
    return value == PaymentMethod.upi ? {
        upi: null
    } : value == PaymentMethod.netbanking ? {
        netbanking: null
    } : value == PaymentMethod.card ? {
        card: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): {
    phishing: null;
} | {
    passwords: null;
} | {
    safeBrowsing: null;
} | {
    mobileSecurity: null;
} | {
    emailSafety: null;
} | {
    malware: null;
} {
    return value == Category.phishing ? {
        phishing: null
    } : value == Category.passwords ? {
        passwords: null
    } : value == Category.safeBrowsing ? {
        safeBrowsing: null
    } : value == Category.mobileSecurity ? {
        mobileSecurity: null
    } : value == Category.emailSafety ? {
        emailSafety: null
    } : value == Category.malware ? {
        malware: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
